name: Integration

on: push

jobs:
  integration:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
      - name: Get latest JBrowse
        run: mkdir .jbrowse && cd .jbrowse && yarn run jbrowse create --force .
      - name: Figure out where I am
        run: pwd && ls
      - name: Test plugin
        run: yarn run e2e